.PHONY: all

all:
	docker build -t timelib-musl -f Dockerfile.musl .
	docker run --rm -ti -v $(shell pwd):/src timelib-musl /bin/sh -c "make -C /src  -f Makefile.linux cleanup && make -C /src -f Makefile.linux test && make -C /src -f Makefile.linux clean"
	docker build -t timelib-linux .
	docker build -t timelib-windows -f Dockerfile.mingw .
	docker run --rm -ti -v $(shell pwd):/src timelib-linux /bin/sh -c "make -C /src -f Makefile.linux cleanup && make -C /src -f Makefile.linux test"
	docker run --rm -ti -v $(shell pwd):/src timelib-windows /bin/sh -c "make -C /src -f Makefile.mingw cleanup && make -C /src -f Makefile.mingw test"
