.PHONY: all

all:
	docker build -t timelib-linux .
	docker build -t timelib-windows -f Dockerfile.mingw .
	make cleanup
	make
	docker run --rm -ti -v $(shell pwd):/src timelib-linux /bin/sh -c "make -C /src -f Makefile.linux cleanup && make -C /src -f Makefile.linux library"
	docker run --rm -ti -v $(shell pwd):/src timelib-windows /bin/sh -c "make -C /src -f Makefile.mingw cleanup && make -C /src -f Makefile.mingw test"
